// Source: static TypeScript TODO list for Python test parity during migration.

import { describe, expect, test } from "bun:test";

const todoSuites = [
  { path: "test/test_aes.py", tests: [
    "TestAES.test_encrypt",
    "TestAES.test_decrypt_text",
    "TestAES.test_key_expansion",
  ] },
  { path: "test/test_age_restriction.py", tests: [
    "TestAgeRestriction.test_youtube",
    "TestAgeRestriction.test_youporn",
  ] },
  { path: "test/test_all_urls.py", tests: [
    "TestAllURLsMatching.test_youtube_playlist_matching",
    "TestAllURLsMatching.test_youtube_matching",
    "TestAllURLsMatching.test_youtube_channel_matching",
    "TestAllURLsMatching.test_youtube_user_matching",
    "TestAllURLsMatching.test_facebook_matching",
    "TestAllURLsMatching.test_no_duplicates",
    "TestAllURLsMatching.test_vimeo_matching",
    "TestAllURLsMatching.test_soundcloud_not_matching_sets",
    "TestAllURLsMatching.test_tumblr",
    "TestAllURLsMatching.test_pbs",
  ] },
  { path: "test/test_compat.py", tests: [
    "TestCompat.test_compat_passthrough",
    "TestCompat.test_struct_unpack",
  ] },
  { path: "test/test_config.py", tests: [
    "TestConfig.test_config__ENVIRON_DEFAULTS_sanity",
    "TestConfig.test_config_all_environ_values",
    "TestConfig.test_config_default_expected_locations",
    "TestConfig.test_config_default_grouping",
    "TestConfig.test_config_early_exit_commandline",
    "TestConfig.test_config_early_exit_files",
    "TestConfig.test_config_override_commandline",
    "TestConfig.test_config_override_files",
  ] },
  { path: "test/test_cookies.py", tests: [
    "TestCookies.test_get_desktop_environment",
    "TestCookies.test_chrome_cookie_decryptor_linux_derive_key",
    "TestCookies.test_chrome_cookie_decryptor_mac_derive_key",
    "TestCookies.test_chrome_cookie_decryptor_linux_v11",
    "TestCookies.test_chrome_cookie_decryptor_linux_v10_meta24",
    "TestCookies.test_chrome_cookie_decryptor_windows_v10",
    "TestCookies.test_chrome_cookie_decryptor_windows_v10_meta24",
    "TestCookies.test_chrome_cookie_decryptor_mac_v10",
    "TestCookies.test_safari_cookie_parsing",
    "TestLenientSimpleCookie.test_parsing",
    "TestLenientSimpleCookie.test_lenient_parsing",
  ] },
  { path: "test/test_devalue.py", tests: [
    "TestDevalue.test_devalue_parse_equals",
    "TestDevalue.test_devalue_parse_is",
    "TestDevalue.test_devalue_parse_invalid",
    "TestDevalue.test_devalue_parse_cyclical",
    "TestDevalue.test_devalue_parse_revivers",
  ] },
  { path: "test/test_download.py", tests: [
    "TestDownload.test_template",
    "TestDownload.test_template",
  ] },
  { path: "test/test_downloader_external.py", tests: [
    "TestFFmpegFD.test_make_cmd",
  ] },
  { path: "test/test_downloader_http.py", tests: [
    "TestHttpFD.test_regular",
    "TestHttpFD.test_chunked",
  ] },
  { path: "test/test_execution.py", tests: [
    "TestExecution.test_main_exec",
    "TestExecution.test_import",
    "TestExecution.test_module_exec",
    "TestExecution.test_cmdline_umlauts",
    "TestExecution.test_lazy_extractors",
  ] },
  { path: "test/test_http_proxy.py", tests: [
    "TestHTTPProxy.test_http_no_auth",
    "TestHTTPProxy.test_http_auth",
    "TestHTTPProxy.test_http_bad_auth",
    "TestHTTPProxy.test_http_source_address",
    "TestHTTPProxy.test_https",
    "TestHTTPProxy.test_https_verify_failed",
    "TestHTTPProxy.test_http_with_idn",
    "TestHTTPConnectProxy.test_http_connect_no_auth",
    "TestHTTPConnectProxy.test_http_connect_auth",
    "TestHTTPConnectProxy.test_http_connect_bad_auth",
    "TestHTTPConnectProxy.test_http_connect_source_address",
    "TestHTTPConnectProxy.test_https_connect_proxy",
    "TestHTTPConnectProxy.test_https_connect_verify_failed",
    "TestHTTPConnectProxy.test_https_connect_proxy_auth",
  ] },
  { path: "test/test_InfoExtractor.py", tests: [
    "TestInfoExtractorNetwork.test_extract_m3u8_formats",
    "TestInfoExtractorNetwork.test_extract_m3u8_formats_warning",
  ] },
  { path: "test/test_jsc/test_ejs_integration.py", tests: [
    "test_bulk_requests",
    "test_using_cached_player",
  ] },
  { path: "test/test_jsc/test_provider.py", tests: [
    "TestJsChallengeProvider.test_base_type",
    "TestJsChallengeProvider.test_create_provider_missing_bulk_solve_method",
    "TestJsChallengeProvider.test_create_provider_missing_available_method",
    "TestJsChallengeProvider.test_barebones_provider",
    "TestJsChallengeProvider.test_example_provider_success",
    "TestJsChallengeProvider.test_provider_unsupported_challenge_type",
    "TestJsChallengeProvider.test_provider_get_player",
    "TestJsChallengeProvider.test_provider_get_player_error",
    "TestJsChallengeProvider.test_require_class_end_with_suffix",
    "test_register_provider",
    "test_register_preference",
  ] },
  { path: "test/test_jsinterp.py", tests: [
    "TestJSInterpreter.test_basic",
    "TestJSInterpreter.test_add",
    "TestJSInterpreter.test_sub",
    "TestJSInterpreter.test_mul",
    "TestJSInterpreter.test_div",
    "TestJSInterpreter.test_mod",
    "TestJSInterpreter.test_exp",
    "TestJSInterpreter.test_calc",
    "TestJSInterpreter.test_empty_return",
    "TestJSInterpreter.test_morespace",
    "TestJSInterpreter.test_strange_chars",
    "TestJSInterpreter.test_operators",
    "TestJSInterpreter.test_string_concat",
    "TestJSInterpreter.test_array_access",
    "TestJSInterpreter.test_parens",
    "TestJSInterpreter.test_quotes",
    "TestJSInterpreter.test_assignments",
    "TestJSInterpreter.test_comments",
    "TestJSInterpreter.test_precedence",
    "TestJSInterpreter.test_builtins",
    "TestJSInterpreter.test_date",
    "TestJSInterpreter.test_call",
    "TestJSInterpreter.test_if",
    "TestJSInterpreter.test_for_loop",
    "TestJSInterpreter.test_switch",
    "TestJSInterpreter.test_switch_default",
    "TestJSInterpreter.test_try",
    "TestJSInterpreter.test_catch",
    "TestJSInterpreter.test_finally",
    "TestJSInterpreter.test_nested_try",
    "TestJSInterpreter.test_for_loop_continue",
    "TestJSInterpreter.test_for_loop_break",
    "TestJSInterpreter.test_for_loop_try",
    "TestJSInterpreter.test_literal_list",
    "TestJSInterpreter.test_comma",
    "TestJSInterpreter.test_void",
    "TestJSInterpreter.test_return_function",
    "TestJSInterpreter.test_null",
    "TestJSInterpreter.test_undefined",
    "TestJSInterpreter.test_object",
    "TestJSInterpreter.test_regex",
    "TestJSInterpreter.test_replace",
    "TestJSInterpreter.test_char_code_at",
    "TestJSInterpreter.test_bitwise_operators_overflow",
    "TestJSInterpreter.test_bitwise_operators_typecast",
    "TestJSInterpreter.test_negative",
    "TestJSInterpreter.test_packed",
    "TestJSInterpreter.test_join",
    "TestJSInterpreter.test_split",
    "TestJSInterpreter.test_slice",
    "TestJSInterpreter.test_splice",
    "TestJSInterpreter.test_int_to_int32",
    "TestJSInterpreter.test_js_number_to_string",
    "TestJSInterpreter.test_extract_function",
    "TestJSInterpreter.test_extract_function_with_global_stack",
    "TestJSInterpreter.test_extract_object",
    "TestJSInterpreter.test_increment_decrement",
    "TestJSInterpreter.test_nested_function_scoping",
    "TestJSInterpreter.test_undefined_varnames",
  ] },
  { path: "test/test_netrc.py", tests: [
    "TestNetRc.test_netrc_present",
  ] },
  { path: "test/test_networking_utils.py", tests: [
    "TestNetworkingUtils.test_make_socks_proxy_opts",
    "TestNetworkingUtils.test_make_socks_proxy_unknown",
    "TestNetworkingUtils.test_load_certifi",
    "TestInstanceStoreMixin.test_mixin",
    "TestNetworkingExceptions.test_redirect_http_error",
  ] },
  { path: "test/test_networking.py", tests: [
    "TestHTTPRequestHandler.test_verify_cert",
    "TestHTTPRequestHandler.test_ssl_error",
    "TestHTTPRequestHandler.test_legacy_ssl_extension",
    "TestHTTPRequestHandler.test_legacy_ssl_support",
    "TestHTTPRequestHandler.test_percent_encode",
    "TestHTTPRequestHandler.test_remove_dot_segments",
    "TestHTTPRequestHandler.test_unicode_path_redirection",
    "TestHTTPRequestHandler.test_raise_http_error",
    "TestHTTPRequestHandler.test_response_url",
    "TestHTTPRequestHandler.test_redirect",
    "TestHTTPRequestHandler.test_request_cookie_header",
    "TestHTTPRequestHandler.test_redirect_loop",
    "TestHTTPRequestHandler.test_incompleteread",
    "TestHTTPRequestHandler.test_cookies",
    "TestHTTPRequestHandler.test_cookie_sync_only_cookiejar",
    "TestHTTPRequestHandler.test_cookie_sync_delete_cookie",
    "TestHTTPRequestHandler.test_headers",
    "TestHTTPRequestHandler.test_read_timeout",
    "TestHTTPRequestHandler.test_connect_timeout",
    "TestHTTPRequestHandler.test_source_address",
    "TestHTTPRequestHandler.test_gzip_trailing_garbage",
    "TestHTTPRequestHandler.test_brotli",
    "TestHTTPRequestHandler.test_deflate",
    "TestHTTPRequestHandler.test_gzip",
    "TestHTTPRequestHandler.test_multiple_encodings",
    "TestHTTPRequestHandler.test_unsupported_encoding",
    "TestHTTPRequestHandler.test_read",
    "TestHTTPRequestHandler.test_request_disable_proxy",
    "TestHTTPRequestHandler.test_noproxy",
    "TestHTTPRequestHandler.test_allproxy",
    "TestHTTPRequestHandler.test_keep_header_casing",
    "TestHTTPRequestHandler.test_partial_read_then_full_read",
    "TestHTTPRequestHandler.test_partial_read_greater_than_response_then_full_read",
    "TestClientCertificate.test_certificate_combined_nopass",
    "TestClientCertificate.test_certificate_nocombined_nopass",
    "TestClientCertificate.test_certificate_combined_pass",
    "TestClientCertificate.test_certificate_nocombined_pass",
    "TestHTTPImpersonateRequestHandler.test_supported_impersonate_targets",
    "TestHTTPImpersonateRequestHandler.test_response_extensions",
    "TestHTTPImpersonateRequestHandler.test_http_error_response_extensions",
    "TestRequestHandlerMisc.test_remove_logging_handler",
    "TestRequestHandlerMisc.test_wrap_request_errors",
    "TestUrllibRequestHandler.test_file_urls",
    "TestUrllibRequestHandler.test_data_uri_auto_close",
    "TestUrllibRequestHandler.test_http_response_auto_close",
    "TestUrllibRequestHandler.test_data_uri_partial_read_then_full_read",
    "TestUrllibRequestHandler.test_data_uri_partial_read_greater_than_response_then_full_read",
    "TestUrllibRequestHandler.test_http_error_returns_content",
    "TestUrllibRequestHandler.test_verify_cert_error_text",
    "TestUrllibRequestHandler.test_httplib_validation_errors",
    "TestRequestsRequestHandler.test_request_error_mapping",
    "TestRequestsRequestHandler.test_response_error_mapping",
    "TestRequestsRequestHandler.test_close",
    "TestRequestsRequestHandler.test_http_response_auto_close",
    "TestCurlCFFIRequestHandler.test_impersonate",
    "TestCurlCFFIRequestHandler.test_headers",
    "TestCurlCFFIRequestHandler.test_response_error_mapping",
    "TestCurlCFFIRequestHandler.test_request_error_mapping",
    "TestCurlCFFIRequestHandler.test_response_reader",
    "TestCurlCFFIRequestHandler.test_http_response_auto_close",
    "TestRequestHandlerValidation.test_no_proxy",
    "TestRequestHandlerValidation.test_empty_proxy",
    "TestRequestHandlerValidation.test_invalid_proxy_url",
    "TestRequestHandlerValidation.test_url_scheme",
    "TestRequestHandlerValidation.test_proxy_key",
    "TestRequestHandlerValidation.test_proxy_scheme",
    "TestRequestHandlerValidation.test_extension",
    "TestRequestHandlerValidation.test_invalid_request_type",
    "TestRequestDirector.test_handler_operations",
    "TestRequestDirector.test_send",
    "TestRequestDirector.test_unsupported_handlers",
    "TestRequestDirector.test_unexpected_error",
    "TestRequestDirector.test_preference",
    "TestRequestDirector.test_close",
    "TestYoutubeDLNetworking.test_compat_opener",
    "TestYoutubeDLNetworking.test_proxy",
    "TestYoutubeDLNetworking.test_compat_request",
    "TestYoutubeDLNetworking.test_extract_basic_auth",
    "TestYoutubeDLNetworking.test_sanitize_url",
    "TestYoutubeDLNetworking.test_file_urls_error",
    "TestYoutubeDLNetworking.test_websocket_unavailable_error",
    "TestYoutubeDLNetworking.test_legacy_server_connect_error",
    "TestYoutubeDLNetworking.test_unsupported_impersonate_target",
    "TestYoutubeDLNetworking.test_unsupported_impersonate_extension",
    "TestYoutubeDLNetworking.test_raise_impersonate_error",
    "TestYoutubeDLNetworking.test_pass_impersonate_param",
    "TestYoutubeDLNetworking.test_get_impersonate_targets",
    "test_clean_proxy",
    "test_clean_proxy_header",
    "test_clean_header",
    "test_build_handler_params",
    "test_client_certificate",
    "test_urllib_file_urls",
    "test_compat_opt_prefer_urllib",
    "TestRequest.test_query",
    "TestRequest.test_method",
    "TestRequest.test_request_helpers",
    "TestRequest.test_headers",
    "TestRequest.test_data_type",
    "TestRequest.test_content_length_header",
    "TestRequest.test_content_type_header",
    "TestRequest.test_update_req",
    "TestRequest.test_proxies",
    "TestRequest.test_extensions",
    "TestRequest.test_copy",
    "TestRequest.test_url",
    "TestResponse.test_reason",
    "TestResponse.test_headers",
    "TestResponse.test_get_header",
    "TestResponse.test_compat",
    "TestResponse.test_auto_close",
    "TestResponse.test_close",
    "TestImpersonateTarget.test_target_from_str",
    "TestImpersonateTarget.test_target_from_invalid_str",
    "TestImpersonateTarget.test_str",
    "TestImpersonateTarget.test_invalid_impersonate_target",
    "TestImpersonateTarget.test_impersonate_target_in",
  ] },
  { path: "test/test_overwrites.py", tests: [
    "TestOverwrites.test_default_overwrites",
    "TestOverwrites.test_yes_overwrites",
  ] },
  { path: "test/test_plugins.py", tests: [
    "TestPlugins.test_directories_containing_plugins",
    "TestPlugins.test_extractor_classes",
    "TestPlugins.test_postprocessor_classes",
    "TestPlugins.test_importing_zipped_module",
    "TestPlugins.test_reloading_plugins",
    "TestPlugins.test_extractor_override_plugin",
    "TestPlugins.test_load_all_plugin_types",
    "TestPlugins.test_no_plugin_dirs",
    "TestPlugins.test_set_plugin_dirs",
    "TestPlugins.test_invalid_plugin_dir",
    "TestPlugins.test_append_plugin_dirs",
    "TestPlugins.test_get_plugin_spec",
  ] },
  { path: "test/test_post_hooks.py", tests: [
    "TestPostHooks.test_post_hooks",
    "TestPostHooks.test_post_hook_exception",
  ] },
  { path: "test/test_postprocessors.py", tests: [
    "TestMetadataFromField.test_format_to_regex",
    "TestMetadataFromField.test_field_to_template",
    "TestMetadataFromField.test_metadatafromfield",
    "TestConvertThumbnail.test_escaping",
    "TestExec.test_parse_cmd",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CanGetThroughUnaltered",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithSponsors",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorBlockChapters",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_UniqueNamesForOverlappingSponsors",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithCuts",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithSponsorsAndCuts",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithSponsorCutInTheMiddle",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithCutHidingSponsor",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithAdjacentSponsors",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithAdjacentCuts",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithOverlappingSponsors",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithOverlappingCuts",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithRunsOfOverlappingSponsors",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithRunsOfOverlappingCuts",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_OverlappingSponsorsDifferentTitlesAfterCut",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorsNoLongerOverlapAfterCut",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorsStillOverlapAfterCut",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChapterWithRunsOfOverlappingSponsorsAndCuts",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorOverlapsMultipleChapters",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutOverlapsMultipleChapters",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorsWithinSomeChaptersAndOverlappingOthers",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutsWithinSomeChaptersAndOverlappingOthers",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChaptersAfterLastSponsor",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_ChaptersAfterLastCut",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorStartsAtChapterStart",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutStartsAtChapterStart",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorEndsAtChapterEnd",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutEndsAtChapterEnd",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorCoincidesWithChapters",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutCoincidesWithChapters",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorsAtVideoBoundaries",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutsAtVideoBoundaries",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SponsorsOverlapChaptersAtVideoBoundaries",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_CutsOverlapChaptersAtVideoBoundaries",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_EverythingSponsored",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_EverythingCut",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinyChaptersInTheOriginalArePreserved",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinySponsorsAreIgnored",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinyChaptersResultingFromCutsAreIgnored",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SingleTinyChapterIsPreserved",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinyChapterAtTheStartPrependedToTheNext",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinyChaptersResultingFromSponsorOverlapAreIgnored",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinySponsorsOverlapsAreIgnored",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_TinySponsorsPrependedToTheNextSponsor",
    "TestModifyChaptersPP.test_remove_marked_arrange_sponsors_SmallestSponsorInTheOverlapGetsNamed",
    "TestModifyChaptersPP.test_make_concat_opts_CommonCase",
    "TestModifyChaptersPP.test_make_concat_opts_NoZeroDurationChunkAtVideoStart",
    "TestModifyChaptersPP.test_make_concat_opts_NoZeroDurationChunkAtVideoEnd",
    "TestModifyChaptersPP.test_quote_for_concat_RunsOfQuotes",
    "TestModifyChaptersPP.test_quote_for_concat_QuotesAtStart",
    "TestModifyChaptersPP.test_quote_for_concat_QuotesAtEnd",
  ] },
  { path: "test/test_pot/test_pot_builtin_memorycache.py", tests: [
    "TestMemoryLRUPCS.test_base_type",
    "TestMemoryLRUPCS.test_is_registered",
    "TestMemoryLRUPCS.test_initialization",
    "TestMemoryLRUPCS.test_store_and_get",
    "TestMemoryLRUPCS.test_store_ignore_expired",
    "TestMemoryLRUPCS.test_store_override_existing_key",
    "TestMemoryLRUPCS.test_store_ignore_expired_existing_key",
    "TestMemoryLRUPCS.test_get_key_expired",
    "TestMemoryLRUPCS.test_lru_eviction",
    "TestMemoryLRUPCS.test_delete",
    "TestMemoryLRUPCS.test_use_global_cache_default",
    "TestMemoryLRUPCS.test_fail_max_size_change_global",
    "TestMemoryLRUPCS.test_memory_lru_preference",
  ] },
  { path: "test/test_pot/test_pot_builtin_utils.py", tests: [
    "TestGetWebPoContentBinding.test_get_webpo_content_binding",
    "TestGetWebPoContentBinding.test_extract_visitor_id",
    "TestGetWebPoContentBinding.test_invalid_visitor_id",
    "TestGetWebPoContentBinding.test_no_visitor_id",
    "TestGetWebPoContentBinding.test_invalid_base64",
    "TestGetWebPoContentBinding.test_gvs_video_id_binding_experiment",
  ] },
  { path: "test/test_pot/test_pot_builtin_webpospec.py", tests: [
    "TestWebPoPCSP.test_base_type",
    "TestWebPoPCSP.test_init",
    "TestWebPoPCSP.test_is_registered",
    "TestWebPoPCSP.test_not_supports",
    "TestWebPoPCSP.test_generate_key_bindings",
    "TestWebPoPCSP.test_no_bind_visitor_id",
    "TestWebPoPCSP.test_default_ttl",
    "TestWebPoPCSP.test_write_policy",
  ] },
  { path: "test/test_pot/test_pot_director.py", tests: [
    "TestPoTokenCache.test_cache_success",
    "TestPoTokenCache.test_unsupported_cache_spec_no_fallback",
    "TestPoTokenCache.test_unsupported_cache_spec_fallback",
    "TestPoTokenCache.test_invalid_cache_spec_no_fallback",
    "TestPoTokenCache.test_invalid_cache_spec_fallback",
    "TestPoTokenCache.test_unavailable_cache_spec_no_fallback",
    "TestPoTokenCache.test_unavailable_cache_spec_fallback",
    "TestPoTokenCache.test_unexpected_error_cache_spec",
    "TestPoTokenCache.test_unexpected_error_cache_spec_fallback",
    "TestPoTokenCache.test_key_bindings_spec_provider",
    "TestPoTokenCache.test_cache_provider_preferences",
    "TestPoTokenCache.test_secondary_cache_provider_hit",
    "TestPoTokenCache.test_cache_provider_no_hits",
    "TestPoTokenCache.test_get_invalid_po_token_response",
    "TestPoTokenCache.test_store_invalid_po_token_response",
    "TestPoTokenCache.test_store_write_policy",
    "TestPoTokenCache.test_store_write_first_policy_cache_spec",
    "TestPoTokenCache.test_store_write_all_policy_cache_spec",
    "TestPoTokenCache.test_expires_at_pot_response",
    "TestPoTokenCache.test_expires_at_default_spec",
    "TestPoTokenCache.test_cache_provider_error_no_fallback",
    "TestPoTokenCache.test_cache_provider_error_fallback",
    "TestPoTokenCache.test_cache_provider_unexpected_error_no_fallback",
    "TestPoTokenCache.test_cache_provider_unexpected_error_fallback",
    "TestPoTokenCache.test_cache_provider_unavailable_no_fallback",
    "TestPoTokenCache.test_cache_provider_unavailable_fallback",
    "TestPoTokenCache.test_available_not_called",
    "TestPoTokenCache.test_available_called_trace",
    "TestPoTokenCache.test_close",
    "TestPoTokenRequestDirector.test_request_pot_success",
    "TestPoTokenRequestDirector.test_request_and_cache",
    "TestPoTokenRequestDirector.test_bypass_cache",
    "TestPoTokenRequestDirector.test_clean_pot_generate",
    "TestPoTokenRequestDirector.test_clean_pot_cache",
    "TestPoTokenRequestDirector.test_cache_expires_at_none",
    "TestPoTokenRequestDirector.test_cache_expires_at_positive",
    "TestPoTokenRequestDirector.test_not_cache_expires_at",
    "TestPoTokenRequestDirector.test_no_providers",
    "TestPoTokenRequestDirector.test_try_cache_no_providers",
    "TestPoTokenRequestDirector.test_close",
    "TestPoTokenRequestDirector.test_pot_provider_preferences",
    "TestPoTokenRequestDirector.test_unsupported_request_no_fallback",
    "TestPoTokenRequestDirector.test_unsupported_request_fallback",
    "TestPoTokenRequestDirector.test_unavailable_request_no_fallback",
    "TestPoTokenRequestDirector.test_unavailable_request_fallback",
    "TestPoTokenRequestDirector.test_available_not_called",
    "TestPoTokenRequestDirector.test_available_called_trace",
    "TestPoTokenRequestDirector.test_provider_error_no_fallback_unexpected",
    "TestPoTokenRequestDirector.test_provider_error_no_fallback_expected",
    "TestPoTokenRequestDirector.test_provider_error_fallback",
    "TestPoTokenRequestDirector.test_provider_unexpected_error_no_fallback",
    "TestPoTokenRequestDirector.test_provider_unexpected_error_fallback",
    "TestPoTokenRequestDirector.test_invalid_po_token_response_type",
    "TestPoTokenRequestDirector.test_invalid_po_token_response",
    "TestPoTokenRequestDirector.test_copy_request_provider",
    "test_validate_cache_spec",
    "test_clean_pot_fail",
    "test_clean_pot",
    "test_validate_pot_response",
    "test_built_in_provider",
  ] },
  { path: "test/test_pot/test_pot_framework.py", tests: [
    "TestPoTokenProvider.test_base_type",
    "TestPoTokenProvider.test_create_provider_missing_fetch_method",
    "TestPoTokenProvider.test_create_provider_missing_available_method",
    "TestPoTokenProvider.test_barebones_provider",
    "TestPoTokenProvider.test_example_provider_success",
    "TestPoTokenProvider.test_provider_unsupported_context",
    "TestPoTokenProvider.test_provider_unsupported_client",
    "TestPoTokenProvider.test_provider_unsupported_proxy_scheme",
    "TestPoTokenProvider.test_provider_ignore_external_request_features",
    "TestPoTokenProvider.test_provider_unsupported_external_request_source_address",
    "TestPoTokenProvider.test_provider_supported_external_request_source_address",
    "TestPoTokenProvider.test_provider_unsupported_external_request_tls_verification",
    "TestPoTokenProvider.test_provider_supported_external_request_tls_verification",
    "TestPoTokenProvider.test_provider_request_webpage",
    "TestPoTokenProvider.test_provider_request_webpage_override",
    "TestPoTokenProvider.test_provider_request_webpage_no_log",
    "TestPoTokenProvider.test_provider_request_webpage_no_pot_request",
    "TestPoTokenProvider.test_get_config_arg",
    "TestPoTokenProvider.test_require_class_end_with_suffix",
    "TestPoTokenCacheProvider.test_base_type",
    "TestPoTokenCacheProvider.test_create_provider_missing_get_method",
    "TestPoTokenCacheProvider.test_create_provider_missing_store_method",
    "TestPoTokenCacheProvider.test_create_provider_missing_delete_method",
    "TestPoTokenCacheProvider.test_create_provider_missing_is_available_method",
    "TestPoTokenCacheProvider.test_barebones_provider",
    "TestPoTokenCacheProvider.test_create_provider_example",
    "TestPoTokenCacheProvider.test_get_config_arg",
    "TestPoTokenCacheProvider.test_require_class_end_with_suffix",
    "TestPoTokenCacheSpecProvider.test_base_type",
    "TestPoTokenCacheSpecProvider.test_create_provider_missing_supports_method",
    "TestPoTokenCacheSpecProvider.test_create_provider_barebones",
    "TestPoTokenCacheSpecProvider.test_create_provider_example",
    "TestPoTokenCacheSpecProvider.test_get_config_arg",
    "TestPoTokenCacheSpecProvider.test_require_class_end_with_suffix",
    "TestPoTokenRequest.test_copy_request",
    "test_provider_bug_report_message",
    "test_register_provider",
    "test_register_pot_preference",
    "test_register_cache_provider",
    "test_register_cache_provider_spec",
    "test_register_cache_provider_preference",
    "test_logger_log_level",
    "test_configuration_arg",
  ] },
  { path: "test/test_socks.py", tests: [
    "TestSocks4Proxy.test_socks4_no_auth",
    "TestSocks4Proxy.test_socks4_auth",
    "TestSocks4Proxy.test_socks4a_ipv4_target",
    "TestSocks4Proxy.test_socks4a_domain_target",
    "TestSocks4Proxy.test_ipv4_client_source_address",
    "TestSocks4Proxy.test_socks4_errors",
    "TestSocks4Proxy.test_ipv6_socks4_proxy",
    "TestSocks4Proxy.test_timeout",
    "TestSocks5Proxy.test_socks5_no_auth",
    "TestSocks5Proxy.test_socks5_user_pass",
    "TestSocks5Proxy.test_socks5_ipv4_target",
    "TestSocks5Proxy.test_socks5_domain_target",
    "TestSocks5Proxy.test_socks5h_domain_target",
    "TestSocks5Proxy.test_socks5h_ip_target",
    "TestSocks5Proxy.test_socks5_ipv6_destination",
    "TestSocks5Proxy.test_ipv6_socks5_proxy",
    "TestSocks5Proxy.test_ipv4_client_source_address",
    "TestSocks5Proxy.test_socks5_errors",
    "TestSocks5Proxy.test_timeout",
  ] },
  { path: "test/test_subtitles.py", tests: [
    "TestYoutubeSubtitles.test_youtube_allsubtitles",
    "TestYoutubeSubtitles.test_youtube_subtitles_ttml_format",
    "TestYoutubeSubtitles.test_youtube_subtitles_vtt_format",
    "TestYoutubeSubtitles.test_youtube_subtitles_json3_format",
    "TestYoutubeSubtitles.test_youtube_automatic_captions",
    "TestYoutubeSubtitles.test_youtube_translated_subtitles",
    "TestYoutubeSubtitles.test_youtube_nosubtitles",
    "TestDailymotionSubtitles.test_allsubtitles",
    "TestDailymotionSubtitles.test_nosubtitles",
    "TestTedSubtitles.test_allsubtitles",
    "TestVimeoSubtitles.test_allsubtitles",
    "TestVimeoSubtitles.test_nosubtitles",
    "TestWallaSubtitles.test_allsubtitles",
    "TestWallaSubtitles.test_nosubtitles",
    "TestCeskaTelevizeSubtitles.test_allsubtitles",
    "TestCeskaTelevizeSubtitles.test_nosubtitles",
    "TestLyndaSubtitles.test_allsubtitles",
    "TestNPOSubtitles.test_allsubtitles",
    "TestNRKSubtitles.test_allsubtitles",
    "TestRaiPlaySubtitles.test_subtitles_key",
    "TestRaiPlaySubtitles.test_subtitles_array_key",
    "TestThePlatformSubtitles.test_allsubtitles",
    "TestThePlatformFeedSubtitles.test_allsubtitles",
    "TestRtveSubtitles.test_allsubtitles",
    "TestDemocracynowSubtitles.test_allsubtitles",
    "TestDemocracynowSubtitles.test_subtitles_in_page",
    "TestPBSSubtitles.test_allsubtitles",
    "TestPBSSubtitles.test_subtitles_dfxp_format",
    "TestPBSSubtitles.test_subtitles_vtt_format",
    "TestPBSSubtitles.test_subtitles_srt_format",
    "TestPBSSubtitles.test_subtitles_sami_format",
  ] },
  { path: "test/test_traversal.py", tests: [
    "TestTraversal.test_traversal_base",
    "TestTraversal.test_traversal_ellipsis",
    "TestTraversal.test_traversal_function",
    "TestTraversal.test_traversal_set",
    "TestTraversal.test_traversal_slice",
    "TestTraversal.test_traversal_alternatives",
    "TestTraversal.test_traversal_branching_nesting",
    "TestTraversal.test_traversal_dict",
    "TestTraversal.test_traversal_default",
    "TestTraversal.test_traversal_branching",
    "TestTraversal.test_traversal_expected_type",
    "TestTraversal.test_traversal_get_all",
    "TestTraversal.test_traversal_casesense",
    "TestTraversal.test_traversal_traverse_string",
    "TestTraversal.test_traversal_re",
    "TestTraversal.test_traversal_xml_etree",
    "TestTraversal.test_traversal_unbranching",
    "TestTraversal.test_traversal_morsel",
    "TestTraversal.test_traversal_filter",
    "TestTraversalHelpers.test_traversal_require",
    "TestTraversalHelpers.test_subs_list_to_dict",
    "TestTraversalHelpers.test_trim_str",
    "TestTraversalHelpers.test_unpack",
    "TestTraversalHelpers.test_find_element",
    "TestTraversalHelpers.test_find_elements",
    "TestDictGet.test_dict_get",
  ] },
  { path: "test/test_update.py", tests: [
    "TestUpdate.test_update_spec",
    "TestUpdate.test_query_update",
  ] },
  { path: "test/test_utils.py", tests: [
    "TestUtil.test_timeconvert",
    "TestUtil.test_sanitize_filename",
    "TestUtil.test_sanitize_filename_restricted",
    "TestUtil.test_sanitize_ids",
    "TestUtil.test_sanitize_path",
    "TestUtil.test_sanitize_url",
    "TestUtil.test_expand_path",
    "TestUtil.test_prepend_extension",
    "TestUtil.test_replace_extension",
    "TestUtil.test_subtitles_filename",
    "TestUtil.test_remove_start",
    "TestUtil.test_remove_end",
    "TestUtil.test_remove_quotes",
    "TestUtil.test_ordered_set",
    "TestUtil.test_unescape_html",
    "TestUtil.test_date_from_str",
    "TestUtil.test_datetime_from_str",
    "TestUtil.test_datetime_round",
    "TestUtil.test_strftime_or_none",
    "TestUtil.test_daterange",
    "TestUtil.test_unified_dates",
    "TestUtil.test_unified_timestamps",
    "TestUtil.test_determine_ext",
    "TestUtil.test_find_xpath_attr",
    "TestUtil.test_xpath_with_ns",
    "TestUtil.test_xpath_element",
    "TestUtil.test_xpath_text",
    "TestUtil.test_xpath_attr",
    "TestUtil.test_smuggle_url",
    "TestUtil.test_shell_quote",
    "TestUtil.test_float_or_none",
    "TestUtil.test_int_or_none",
    "TestUtil.test_str_to_int",
    "TestUtil.test_url_basename",
    "TestUtil.test_base_url",
    "TestUtil.test_urljoin",
    "TestUtil.test_url_or_none",
    "TestUtil.test_parse_age_limit",
    "TestUtil.test_parse_duration",
    "TestUtil.test_fix_xml_ampersands",
    "TestUtil.test_paged_list",
    "TestUtil.test_read_batch_urls",
    "TestUtil.test_urlencode_postdata",
    "TestUtil.test_update_url_query",
    "TestUtil.test_multipart_encode",
    "TestUtil.test_merge_dicts",
    "TestUtil.test_encode_compat_str",
    "TestUtil.test_parse_iso8601",
    "TestUtil.test_strip_jsonp",
    "TestUtil.test_strip_or_none",
    "TestUtil.test_uppercase_escape",
    "TestUtil.test_lowercase_escape",
    "TestUtil.test_limit_length",
    "TestUtil.test_mimetype2ext",
    "TestUtil.test_month_by_name",
    "TestUtil.test_parse_codecs",
    "TestUtil.test_escape_rfc3986",
    "TestUtil.test_normalize_url",
    "TestUtil.test_remove_dot_segments",
    "TestUtil.test_js_to_json_vars_strings",
    "TestUtil.test_js_to_json_realworld",
    "TestUtil.test_js_to_json_edgecases",
    "TestUtil.test_js_to_json_malformed",
    "TestUtil.test_js_to_json_template_literal",
    "TestUtil.test_js_to_json_common_constructors",
    "TestUtil.test_extract_attributes",
    "TestUtil.test_clean_html",
    "TestUtil.test_args_to_str",
    "TestUtil.test_parse_filesize",
    "TestUtil.test_parse_count",
    "TestUtil.test_parse_resolution",
    "TestUtil.test_parse_bitrate",
    "TestUtil.test_version_tuple",
    "TestUtil.test_detect_exe_version",
    "TestUtil.test_age_restricted",
    "TestUtil.test_is_html",
    "TestUtil.test_render_table",
    "TestUtil.test_match_str",
    "TestUtil.test_parse_dfxp_time_expr",
    "TestUtil.test_dfxp2srt",
    "TestUtil.test_cli_option",
    "TestUtil.test_cli_valueless_option",
    "TestUtil.test_cli_bool_option",
    "TestUtil.test_ohdave_rsa_encrypt",
    "TestUtil.test_pkcs1pad",
    "TestUtil.test_encode_base_n",
    "TestUtil.test_caesar",
    "TestUtil.test_rot47",
    "TestUtil.test_urshift",
    "TestUtil.test_get_element_by_class",
    "TestUtil.test_get_element_html_by_class",
    "TestUtil.test_get_element_by_attribute",
    "TestUtil.test_get_element_html_by_attribute",
    "TestUtil.test_get_elements_by_class",
    "TestUtil.test_get_elements_html_by_class",
    "TestUtil.test_get_elements_by_attribute",
    "TestUtil.test_get_elements_html_by_attribute",
    "TestUtil.test_get_elements_text_and_html_by_attribute",
    "TestUtil.test_get_element_text_and_html_by_tag",
    "TestUtil.test_iri_to_uri",
    "TestUtil.test_clean_podcast_url",
    "TestUtil.test_LazyList",
    "TestUtil.test_LazyList_laziness",
    "TestUtil.test_format_bytes",
    "TestUtil.test_hide_login_info",
    "TestUtil.test_locked_file",
    "TestUtil.test_determine_file_encoding",
    "TestUtil.test_get_compatible_ext",
    "TestUtil.test_try_call",
    "TestUtil.test_variadic",
    "TestUtil.test_http_header_dict",
    "TestUtil.test_extract_basic_auth",
    "TestUtil.test_windows_escaping",
    "TestUtil.test_partial_application",
    "TestUtil.test_jwt_encode",
    "TestUtil.test_jwt_decode_hs256",
  ] },
  { path: "test/test_verbose_output.py", tests: [
    "TestVerboseOutput.test_private_info_arg",
    "TestVerboseOutput.test_private_info_shortarg",
    "TestVerboseOutput.test_private_info_eq",
    "TestVerboseOutput.test_private_info_shortarg_eq",
  ] },
  { path: "test/test_websockets.py", tests: [
    "TestWebsSocketRequestHandlerConformance.test_basic_websockets",
    "TestWebsSocketRequestHandlerConformance.test_send_types",
    "TestWebsSocketRequestHandlerConformance.test_verify_cert",
    "TestWebsSocketRequestHandlerConformance.test_ssl_error",
    "TestWebsSocketRequestHandlerConformance.test_legacy_ssl_extension",
    "TestWebsSocketRequestHandlerConformance.test_legacy_ssl_support",
    "TestWebsSocketRequestHandlerConformance.test_percent_encode",
    "TestWebsSocketRequestHandlerConformance.test_remove_dot_segments",
    "TestWebsSocketRequestHandlerConformance.test_raise_http_error",
    "TestWebsSocketRequestHandlerConformance.test_read_timeout",
    "TestWebsSocketRequestHandlerConformance.test_connect_timeout",
    "TestWebsSocketRequestHandlerConformance.test_cookies",
    "TestWebsSocketRequestHandlerConformance.test_cookie_sync_only_cookiejar",
    "TestWebsSocketRequestHandlerConformance.test_cookie_sync_delete_cookie",
    "TestWebsSocketRequestHandlerConformance.test_source_address",
    "TestWebsSocketRequestHandlerConformance.test_response_url",
    "TestWebsSocketRequestHandlerConformance.test_request_headers",
    "TestWebsSocketRequestHandlerConformance.test_keep_header_casing",
    "TestWebsSocketRequestHandlerConformance.test_mtls",
    "TestWebsSocketRequestHandlerConformance.test_request_disable_proxy",
    "TestWebsSocketRequestHandlerConformance.test_noproxy",
    "TestWebsSocketRequestHandlerConformance.test_allproxy",
    "TestWebsocketsRequestHandler.test_request_error_mapping",
    "TestWebsocketsRequestHandler.test_ws_send_error_mapping",
    "TestWebsocketsRequestHandler.test_ws_recv_error_mapping",
  ] },
  { path: "test/test_youtube_lists.py", tests: [
    "TestYoutubeLists.test_youtube_playlist_noplaylist",
    "TestYoutubeLists.test_youtube_mix",
    "TestYoutubeLists.test_youtube_flat_playlist_extraction",
    "TestYoutubeLists.test_youtube_channel_no_uploads",
  ] },
  { path: "test/test_youtube_misc.py", tests: [
    "TestYoutubeMisc.test_youtube_extract",
  ] },
  { path: "test/test_YoutubeDL.py", tests: [
    "TestFormatSelection.test_prefer_free_formats",
    "TestFormatSelection.test_format_selection",
    "TestFormatSelection.test_format_selection_audio",
    "TestFormatSelection.test_format_selection_audio_exts",
    "TestFormatSelection.test_format_selection_video",
    "TestFormatSelection.test_format_selection_by_vcodec_sort",
    "TestFormatSelection.test_format_selection_string_ops",
    "TestFormatSelection.test_audio_only_extractor_format_selection",
    "TestFormatSelection.test_format_not_available",
    "TestFormatSelection.test_format_selection_issue_10083",
    "TestFormatSelection.test_invalid_format_specs",
    "TestFormatSelection.test_format_filtering",
    "TestFormatSelection.test_default_format_spec_without_ffmpeg",
    "TestFormatSelection.test_default_format_spec_with_ffmpeg",
    "TestYoutubeDL.test_subtitles",
    "TestYoutubeDL.test_add_extra_info",
    "TestYoutubeDL.test_prepare_outtmpl_and_filename",
    "TestYoutubeDL.test_format_note",
    "TestYoutubeDL.test_postprocessors",
    "TestYoutubeDL.test_match_filter",
    "TestYoutubeDL.test_playlist_items_selection",
    "TestYoutubeDL.test_selection",
    "TestYoutubeDL.test_do_not_override_ie_key_in_url_transparent",
    "TestYoutubeDL.test_ignoreerrors_for_playlist_with_url_transparent_iterable_entries",
    "TestYoutubeDL.test_header_cookies",
    "TestYoutubeDL.test_infojson_cookies",
    "TestYoutubeDL.test_add_headers_cookie",
    "TestYoutubeDL.test_load_plugins_compat",
    "TestYoutubeDL.test_close_hooks",
  ] },
  { path: "test/test_YoutubeDLCookieJar.py", tests: [
    "TestYoutubeDLCookieJar.test_keep_session_cookies",
    "TestYoutubeDLCookieJar.test_strip_httponly_prefix",
    "TestYoutubeDLCookieJar.test_malformed_cookies",
    "TestYoutubeDLCookieJar.test_get_cookie_header",
    "TestYoutubeDLCookieJar.test_get_cookies_for_url",
  ] },
] as const;

describe("Python test parity TODOs", () => {
  test("unported Python parity cases are represented as static TypeScript TODOs", () => {
    expect(todoSuites.length).toBeGreaterThan(0);
  });

  for (const suite of todoSuites) {
    describe(suite.path, () => {
      for (const name of suite.tests) {
        test.todo(name, () => undefined);
      }
    });
  }
});
