// Source: yt_dlp/cookies.py
// Port note: browser extraction uses Bun APIs where practical. OS keyring integrations are explicit
// unsupported errors until their platform-specific Bun equivalents are implemented.

import { pbkdf2Sync } from "node:crypto";
import { copyFile, mkdtemp, readdir, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";

import { getCookies } from "@steipete/sweet-cookie";
import type {
  Cookie as SweetCookie,
  GetCookiesOptions,
} from "@steipete/sweet-cookie";
import { Database } from "bun:sqlite";

import {
  aesCbcDecryptBytes,
  aesGcmDecryptAndVerifyBytes,
  unpadPkcs7,
} from "./aes.ts";
import { NotImplementedError } from "./errors.ts";

export const CHROMIUM_BASED_BROWSERS = new Set([
  "brave",
  "chrome",
  "chromium",
  "edge",
  "opera",
  "vivaldi",
  "whale",
]);
export const SUPPORTED_BROWSERS = new Set([
  ...CHROMIUM_BASED_BROWSERS,
  "firefox",
  "safari",
]);

export enum LinuxKeyring {
  KWALLET = "KWALLET",
  KWALLET5 = "KWALLET5",
  KWALLET6 = "KWALLET6",
  GNOMEKEYRING = "GNOMEKEYRING",
  BASICTEXT = "BASICTEXT",
}

export enum LinuxDesktopEnvironment {
  OTHER = "OTHER",
  CINNAMON = "CINNAMON",
  DEEPIN = "DEEPIN",
  GNOME = "GNOME",
  KDE3 = "KDE3",
  KDE4 = "KDE4",
  KDE5 = "KDE5",
  KDE6 = "KDE6",
  PANTHEON = "PANTHEON",
  UKUI = "UKUI",
  UNITY = "UNITY",
  XFCE = "XFCE",
  LXQT = "LXQT",
}

export const SUPPORTED_KEYRINGS = Object.keys(LinuxKeyring);

export interface CookieLogger {
  debug(message: string): void;
  info(message: string): void;
  warning(message: string, options?: { onlyOnce?: boolean }): void;
  error(message: string): void;
}

export class YDLLogger implements CookieLogger {
  #warned = new Set<string>();

  debug(message: string): void {
    if (process.env.YTDLB_DEBUG) {
      console.debug(message);
    }
  }

  info(message: string): void {
    console.info(message);
  }

  warning(message: string, options: { onlyOnce?: boolean } = {}): void {
    if (options.onlyOnce && this.#warned.has(message)) {
      return;
    }
    this.#warned.add(message);
    console.warn(message);
  }

  error(message: string): void {
    console.error(message);
  }
}

export class CookieLoadError extends Error {}
export class ParserError extends Error {}

export interface CookieInit {
  name: string;
  value: string;
  domain: string;
  path?: string;
  secure?: boolean;
  expires?: number | null;
  httpOnly?: boolean;
  discard?: boolean;
}

export class Cookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  secure: boolean;
  expires: number | null;
  httpOnly: boolean;
  discard: boolean;

  constructor(init: CookieInit) {
    this.name = init.name;
    this.value = init.value;
    this.domain = init.domain;
    this.path = init.path ?? "/";
    this.secure = Boolean(init.secure);
    this.expires = init.expires ?? null;
    this.httpOnly = Boolean(init.httpOnly);
    this.discard = Boolean(init.discard);
  }

  isExpired(now = Date.now() / 1000): boolean {
    return this.expires !== null && this.expires <= now;
  }
}

export class YoutubeDLCookieJar implements Iterable<Cookie> {
  static readonly HTTPONLY_PREFIX = "#HttpOnly_";
  static readonly ENTRY_LEN = 7;
  static readonly HEADER =
    "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n";

  readonly #cookies: Cookie[] = [];

  constructor(public filename: string | null = null) {}

  [Symbol.iterator](): Iterator<Cookie> {
    return this.#cookies[Symbol.iterator]();
  }

  get length(): number {
    return this.#cookies.length;
  }

  setCookie(cookie: Cookie): void {
    const index = this.#cookies.findIndex(
      (candidate) =>
        candidate.domain === cookie.domain &&
        candidate.path === cookie.path &&
        candidate.name === cookie.name,
    );
    if (index !== -1) {
      this.#cookies.splice(index, 1);
    }
    this.#cookies.push(cookie);
  }

  clear(domain?: string, path?: string, name?: string): void {
    if (!domain) {
      this.#cookies.splice(0);
      return;
    }
    for (let index = this.#cookies.length - 1; index >= 0; index -= 1) {
      const cookie = this.#cookies[index];
      if (!cookie) {
        continue;
      }
      if (
        cookie.domain === domain &&
        (path === undefined || cookie.path === path) &&
        (name === undefined || cookie.name === name)
      ) {
        this.#cookies.splice(index, 1);
      }
    }
  }

  async save(
    filename = this.filename,
    ignoreDiscard = true,
    ignoreExpires = true,
  ): Promise<void> {
    if (!filename) {
      throw new Error("missing filename");
    }
    const now = Date.now() / 1000;
    const lines = [YoutubeDLCookieJar.HEADER];
    for (const cookie of this.#cookies) {
      if (
        (!ignoreDiscard && cookie.discard) ||
        (!ignoreExpires && cookie.isExpired(now))
      ) {
        continue;
      }
      let name = cookie.name;
      let value = cookie.value;
      if (value === undefined || value === null) {
        value = name;
        name = "";
      }
      const domain = `${cookie.httpOnly ? YoutubeDLCookieJar.HTTPONLY_PREFIX : ""}${cookie.domain}`;
      lines.push(
        [
          domain,
          trueOrFalse(cookie.domain.startsWith(".")),
          cookie.path,
          trueOrFalse(cookie.secure),
          cookie.expires ?? 0,
          name,
          value,
        ].join("\t"),
        "\n",
      );
    }
    await Bun.write(filename, lines.join(""));
  }

  async load(
    filename = this.filename,
    _ignoreDiscard = true,
    _ignoreExpires = true,
  ): Promise<void> {
    if (!filename) {
      throw new Error("missing filename");
    }
    const text = await Bun.file(filename).text();
    for (const rawLine of text.split(/\r?\n/)) {
      const line = rawLine.trimEnd();
      if (
        !line ||
        (line.startsWith("#") &&
          !line.startsWith(YoutubeDLCookieJar.HTTPONLY_PREFIX))
      ) {
        continue;
      }
      try {
        this.setCookie(parseNetscapeCookieLine(line));
      } catch (error) {
        if (/^[[{"]/.test(line.trim())) {
          throw new Error(
            "Cookies file must be Netscape formatted, not JSON. See https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp",
          );
        }
        console.warn(
          `WARNING: skipping cookie file entry due to ${error}: ${JSON.stringify(line)}`,
        );
      }
    }
  }

  getCookieHeader(url: string): string | undefined {
    const parsed = new URL(url);
    const now = Date.now() / 1000;
    const pairs = this.#cookies
      .filter((cookie) => cookieMatchesUrl(cookie, parsed, now))
      .map((cookie) => `${cookie.name}=${cookie.value}`);
    return pairs.length ? pairs.join("; ") : undefined;
  }

  getCookiesForUrl(url: string): Cookie[] {
    const parsed = new URL(url);
    const now = Date.now() / 1000;
    return this.#cookies.filter((cookie) =>
      cookieMatchesUrl(cookie, parsed, now),
    );
  }
}

export async function loadCookies(
  cookieFile: string | null | undefined,
  browserSpecification:
    | readonly [string, string?, string?, string?]
    | null
    | undefined,
  _ydl?: unknown,
): Promise<YoutubeDLCookieJar> {
  try {
    const jars: YoutubeDLCookieJar[] = [];
    if (browserSpecification) {
      // Logic change: Sweet Cookie requires a target URL for origin filtering. Browser cookies are
      // now loaded lazily per request URL by YoutubeDL instead of eagerly at startup.
      parseBrowserSpecification(...browserSpecification);
    }
    if (cookieFile) {
      const jar = new YoutubeDLCookieJar(expandPath(cookieFile));
      if (await fileExists(jar.filename)) {
        await jar.load();
      }
      jars.push(jar);
    }
    return mergeCookieJars(jars);
  } catch (error) {
    throw new CookieLoadError(
      `failed to load cookies: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

export async function extractCookiesFromBrowserForUrl(
  browserSpecification: readonly [string, string?, string?, string?],
  url: string,
  logger: CookieLogger = new YDLLogger(),
): Promise<YoutubeDLCookieJar> {
  const [browserName, profile, keyring, container] = parseBrowserSpecification(
    ...browserSpecification,
  );
  if (container && container !== "none") {
    logger.warning(
      "Firefox container selection is not supported by Sweet Cookie; falling back to ytdlb's Firefox cookie reader",
      { onlyOnce: true },
    );
    return filterCookieJarForUrl(
      await extractCookiesFromBrowser(browserName, profile, logger, {
        keyring,
        container,
      }),
      url,
    );
  }

  const options = sweetCookieOptions(browserName, profile, url);
  if (!options) {
    logger.warning(
      `Sweet Cookie does not directly support ${browserName}; falling back to ytdlb's browser cookie reader`,
      { onlyOnce: true },
    );
    return filterCookieJarForUrl(
      await extractCookiesFromBrowser(browserName, profile, logger, {
        keyring,
        container,
      }),
      url,
    );
  }

  try {
    const result = await getCookies(options);
    for (const warning of result.warnings) {
      logger.warning(warning, { onlyOnce: true });
    }
    const jar = new YoutubeDLCookieJar();
    for (const cookie of result.cookies) {
      jar.setCookie(sweetCookieToYtdlbCookie(cookie, url));
    }
    logger.info(
      `Extracted ${jar.length} cookies from ${browserName} for ${new URL(url).origin}`,
    );
    return jar;
  } catch (error) {
    logger.warning(
      `Sweet Cookie failed for ${browserName}: ${error instanceof Error ? error.message : String(error)}`,
      { onlyOnce: true },
    );
    return filterCookieJarForUrl(
      await extractCookiesFromBrowser(browserName, profile, logger, {
        keyring,
        container,
      }),
      url,
    );
  }
}

export async function extractCookiesFromBrowser(
  browserName: string,
  profile?: string | null,
  logger: CookieLogger = new YDLLogger(),
  options: { keyring?: string | null; container?: string | null } = {},
): Promise<YoutubeDLCookieJar> {
  if (browserName === "firefox") {
    return await extractFirefoxCookies(
      profile ?? null,
      options.container ?? null,
      logger,
    );
  }
  if (browserName === "safari") {
    return await extractSafariCookies(profile ?? null, logger);
  }
  if (CHROMIUM_BASED_BROWSERS.has(browserName)) {
    return await extractChromeCookies(
      browserName,
      profile ?? null,
      options.keyring ?? null,
      logger,
    );
  }
  throw new Error(`unknown browser: ${browserName}`);
}

export async function extractFirefoxCookies(
  profile: string | null,
  container: string | null,
  logger: CookieLogger,
): Promise<YoutubeDLCookieJar> {
  logger.info("Extracting cookies from firefox");
  const roots =
    profile === null
      ? firefoxBrowserDirs()
      : isPath(profile)
        ? [profile]
        : firefoxBrowserDirs().map((path) => join(path, profile));
  const cookieDatabasePath = await newest(await firefoxCookieDbs(roots));
  if (!cookieDatabasePath) {
    throw new Error(
      `could not find firefox cookies database in ${roots.map((root) => JSON.stringify(root)).join(", ")}`,
    );
  }

  let containerId: number | null = null;
  if (container !== null && container !== "none") {
    const containersPath = join(dirname(cookieDatabasePath), "containers.json");
    const identities =
      JSON.parse(await Bun.file(containersPath).text()).identities ?? [];
    containerId = identities.find(
      (identity: Record<string, unknown>) =>
        identity.name === container ||
        /^userContext(.+)\.label$/.exec(String(identity.l10nID ?? ""))?.[1] ===
          container,
    )?.userContextId;
    if (typeof containerId !== "number") {
      throw new Error(
        `could not find firefox container "${container}" in containers.json`,
      );
    }
  }

  const tmp = await mkdtemp(join(tmpdir(), "yt_dlp"));
  try {
    const dbPath = await openDatabaseCopy(cookieDatabasePath, tmp);
    const db = new Database(dbPath, { readonly: true });
    try {
      const versionRow = db.query("PRAGMA user_version").get() as Record<
        string,
        number
      > | null;
      const schemaVersion = Object.values(versionRow ?? {})[0] ?? 0;
      if (schemaVersion > 17) {
        logger.warning(
          `Possibly unsupported firefox cookies database version: ${schemaVersion}`,
        );
      }
      const jar = new YoutubeDLCookieJar();
      const rows = queryFirefoxRows(db, container, containerId);
      for (const row of rows) {
        const expiry =
          schemaVersion >= 16 && row.expiry != null
            ? Math.trunc(row.expiry / 1000)
            : row.expiry;
        jar.setCookie(
          new Cookie({
            name: row.name,
            value: row.value,
            domain: row.host,
            path: row.path,
            secure: Boolean(row.isSecure),
            expires: expiry ?? null,
            discard: false,
          }),
        );
      }
      logger.info(`Extracted ${jar.length} cookies from firefox`);
      return jar;
    } finally {
      db.close();
    }
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

export async function extractChromeCookies(
  browserName: string,
  profile: string | null,
  keyring: string | null,
  logger: CookieLogger,
): Promise<YoutubeDLCookieJar> {
  logger.info(`Extracting cookies from ${browserName}`);
  const config = getChromiumBasedBrowserSettings(browserName);
  const searchRoot =
    profile === null
      ? config.browserDir
      : isPath(profile)
        ? profile
        : config.supportsProfiles
          ? join(config.browserDir, profile)
          : config.browserDir;
  const cookieDatabasePath = await newest(
    await findFiles(searchRoot, "Cookies"),
  );
  if (!cookieDatabasePath) {
    throw new Error(
      `could not find ${browserName} cookies database in "${searchRoot}"`,
    );
  }

  const tmp = await mkdtemp(join(tmpdir(), "yt_dlp"));
  try {
    const dbPath = await openDatabaseCopy(cookieDatabasePath, tmp);
    const db = new Database(dbPath, { readonly: true });
    try {
      const columns = getColumnNames(db, "cookies");
      const secureColumn = columns.includes("is_secure")
        ? "is_secure"
        : "secure";
      const rows = db
        .query(
          `SELECT host_key, name, value, encrypted_value, path, expires_utc, ${secureColumn} as is_secure FROM cookies`,
        )
        .all() as ChromeCookieRow[];
      const metaRow = db
        .query('SELECT value FROM meta WHERE key = "version"')
        .get() as { value?: string } | null;
      const decryptor = getCookieDecryptor(
        config.browserDir,
        config.keyringName,
        logger,
        { keyring, metaVersion: Number(metaRow?.value ?? 0) },
      );
      const jar = new YoutubeDLCookieJar();
      let failed = 0;
      for (const row of rows) {
        const [_, cookie] = processChromeCookie(decryptor, row);
        if (!cookie) {
          failed += 1;
          continue;
        }
        jar.setCookie(cookie);
      }
      logger.info(
        `Extracted ${jar.length} cookies from ${browserName}${failed ? ` (${failed} could not be decrypted)` : ""}`,
      );
      return jar;
    } finally {
      db.close();
    }
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

export async function extractSafariCookies(
  profile: string | null,
  logger: CookieLogger,
): Promise<YoutubeDLCookieJar> {
  if (process.platform !== "darwin") {
    throw new Error(`unsupported platform: ${process.platform}`);
  }
  const cookiesPath = profile
    ? expandPath(profile)
    : await newest([
        expandPath("~/Library/Cookies/Cookies.binarycookies"),
        expandPath(
          "~/Library/Containers/com.apple.Safari/Data/Library/Cookies/Cookies.binarycookies",
        ),
      ]);
  if (!cookiesPath || !(await fileExists(cookiesPath))) {
    throw new Error("could not find safari cookies database");
  }
  const jar = parseSafariCookies(
    new Uint8Array(await Bun.file(cookiesPath).arrayBuffer()),
    undefined,
    logger,
  );
  logger.info(`Extracted ${jar.length} cookies from safari`);
  return jar;
}

export class ChromeCookieDecryptor {
  readonly cookieCounts: Record<string, number> = {};
  decrypt(_encryptedValue: Uint8Array): string | null {
    throw new Error("Must be implemented by subclasses");
  }
}

export function getCookieDecryptor(
  browserRoot: string,
  browserKeyringName: string,
  logger: CookieLogger,
  options: { keyring?: string | null; metaVersion?: number | null } = {},
): ChromeCookieDecryptor {
  if (process.platform === "darwin") {
    return new MacChromeCookieDecryptor(
      browserKeyringName,
      logger,
      options.metaVersion ?? 0,
    );
  }
  if (process.platform === "win32") {
    return new WindowsChromeCookieDecryptor(
      browserRoot,
      logger,
      options.metaVersion ?? 0,
    );
  }
  return new LinuxChromeCookieDecryptor(
    browserKeyringName,
    logger,
    options.keyring ?? null,
    options.metaVersion ?? 0,
  );
}

export class LinuxChromeCookieDecryptor extends ChromeCookieDecryptor {
  readonly #v10Key = deriveLinuxKey(Buffer.from("peanuts"));
  readonly #emptyKey = deriveLinuxKey(Buffer.alloc(0));
  readonly #metaVersion: number;

  override readonly cookieCounts = { v10: 0, v11: 0, other: 0 };

  constructor(
    readonly browserKeyringName: string,
    readonly logger: CookieLogger,
    readonly keyring: string | null,
    metaVersion: number,
  ) {
    super();
    this.#metaVersion = metaVersion;
  }

  static deriveKey(password: Uint8Array): Buffer {
    return deriveLinuxKey(password);
  }

  override decrypt(encryptedValue: Uint8Array): string | null {
    const version = Buffer.from(encryptedValue.subarray(0, 3)).toString();
    const ciphertext = encryptedValue.subarray(3);
    if (version === "v10") {
      this.cookieCounts.v10 += 1;
      return decryptAesCbcMulti(
        ciphertext,
        [this.#v10Key, this.#emptyKey],
        this.logger,
        undefined,
        this.#metaVersion >= 24,
      );
    }
    if (version === "v11") {
      this.cookieCounts.v11 += 1;
      const key = this.getV11Key();
      return key
        ? decryptAesCbcMulti(
            ciphertext,
            [key, this.#emptyKey],
            this.logger,
            undefined,
            this.#metaVersion >= 24,
          )
        : null;
    }
    this.cookieCounts.other += 1;
    this.logger.warning(`unknown cookie version: "${version}"`, {
      onlyOnce: true,
    });
    return null;
  }

  private getV11Key(): Buffer | null {
    const password = getLinuxKeyringPassword(
      this.browserKeyringName,
      this.keyring,
      this.logger,
    );
    return password ? deriveLinuxKey(password) : null;
  }
}

export class MacChromeCookieDecryptor extends ChromeCookieDecryptor {
  readonly #key: Buffer | null;
  readonly #metaVersion: number;
  override readonly cookieCounts = { v10: 0, other: 0 };

  constructor(
    browserKeyringName: string,
    readonly logger: CookieLogger,
    metaVersion: number,
  ) {
    super();
    const password = getMacKeyringPassword(browserKeyringName, logger);
    this.#key = password ? MacChromeCookieDecryptor.deriveKey(password) : null;
    this.#metaVersion = metaVersion;
  }

  static deriveKey(password: Uint8Array): Buffer {
    return pbkdf2Sha1(password, Buffer.from("saltysalt"), 1003, 16);
  }

  override decrypt(encryptedValue: Uint8Array): string | null {
    const version = Buffer.from(encryptedValue.subarray(0, 3)).toString();
    const ciphertext = encryptedValue.subarray(3);
    if (version === "v10") {
      this.cookieCounts.v10 += 1;
      return this.#key
        ? decryptAesCbcMulti(
            ciphertext,
            [this.#key],
            this.logger,
            undefined,
            this.#metaVersion >= 24,
          )
        : null;
    }
    this.cookieCounts.other += 1;
    return Buffer.from(encryptedValue).toString();
  }
}

export class WindowsChromeCookieDecryptor extends ChromeCookieDecryptor {
  readonly #key: Buffer | null;
  readonly #metaVersion: number;
  override readonly cookieCounts = { v10: 0, other: 0 };

  constructor(
    browserRoot: string,
    readonly logger: CookieLogger,
    metaVersion: number,
  ) {
    super();
    this.#key = getWindowsV10Key(browserRoot, logger);
    this.#metaVersion = metaVersion;
  }

  override decrypt(encryptedValue: Uint8Array): string | null {
    const version = Buffer.from(encryptedValue.subarray(0, 3)).toString();
    const ciphertext = encryptedValue.subarray(3);
    if (version === "v10") {
      this.cookieCounts.v10 += 1;
      if (!this.#key) {
        this.logger.warning("cannot decrypt v10 cookies: no key found", {
          onlyOnce: true,
        });
        return null;
      }
      const nonceLength = 12;
      const tagLength = 16;
      return decryptAesGcm(
        ciphertext.subarray(nonceLength, ciphertext.length - tagLength),
        this.#key,
        ciphertext.subarray(0, nonceLength),
        ciphertext.subarray(ciphertext.length - tagLength),
        this.logger,
        this.#metaVersion >= 24,
      );
    }
    this.cookieCounts.other += 1;
    return decryptWindowsDpapi(encryptedValue, this.logger)?.toString() ?? null;
  }
}

export function pbkdf2Sha1(
  password: Uint8Array,
  salt: Uint8Array,
  iterations: number,
  keyLength: number,
): Buffer {
  return pbkdf2Sync(password, salt, iterations, keyLength, "sha1");
}

export function decryptAesCbcMulti(
  ciphertext: Uint8Array,
  keys: readonly Uint8Array[],
  logger: CookieLogger,
  initializationVector = Buffer.alloc(16, " "),
  hashPrefix = false,
): string | null {
  for (const key of keys) {
    const plaintext = unpadPkcs7(
      aesCbcDecryptBytes(
        new Uint8Array(ciphertext),
        new Uint8Array(key),
        new Uint8Array(initializationVector),
      ),
    );
    const decoded = decodeUtf8Maybe(
      hashPrefix ? plaintext.subarray(32) : plaintext,
    );
    if (decoded !== null) {
      return decoded;
    }
  }
  logger.warning(
    "failed to decrypt cookie (AES-CBC) because UTF-8 decoding failed. Possibly the key is wrong?",
    { onlyOnce: true },
  );
  return null;
}

export function decryptAesGcm(
  ciphertext: Uint8Array,
  key: Uint8Array,
  nonce: Uint8Array,
  authenticationTag: Uint8Array,
  logger: CookieLogger,
  hashPrefix = false,
): string | null {
  try {
    const plaintext = aesGcmDecryptAndVerifyBytes(
      new Uint8Array(ciphertext),
      new Uint8Array(key),
      new Uint8Array(authenticationTag),
      new Uint8Array(nonce),
    );
    const decoded = decodeUtf8Maybe(
      hashPrefix ? plaintext.subarray(32) : plaintext,
    );
    if (decoded !== null) {
      return decoded;
    }
  } catch {
    logger.warning(
      "failed to decrypt cookie (AES-GCM) because the MAC check failed. Possibly the key is wrong?",
      { onlyOnce: true },
    );
    return null;
  }
  logger.warning(
    "failed to decrypt cookie (AES-GCM) because UTF-8 decoding failed. Possibly the key is wrong?",
    { onlyOnce: true },
  );
  return null;
}

export class DataParser {
  cursor = 0;
  constructor(
    readonly data: Uint8Array,
    readonly logger: CookieLogger,
  ) {}

  readBytes(numBytes: number): Uint8Array {
    if (numBytes < 0) {
      throw new ParserError(`invalid read of ${numBytes} bytes`);
    }
    const end = this.cursor + numBytes;
    if (end > this.data.length) {
      throw new ParserError("reached end of input");
    }
    const out = this.data.subarray(this.cursor, end);
    this.cursor = end;
    return out;
  }

  expectBytes(expectedValue: Uint8Array, message: string): void {
    const value = this.readBytes(expectedValue.length);
    if (!Buffer.from(value).equals(Buffer.from(expectedValue))) {
      throw new ParserError(
        `unexpected value: ${Buffer.from(value).toString("hex")} != ${Buffer.from(expectedValue).toString("hex")} (${message})`,
      );
    }
  }

  readUint(bigEndian = false): number {
    const data = Buffer.from(this.readBytes(4));
    return bigEndian ? data.readUInt32BE(0) : data.readUInt32LE(0);
  }

  readDouble(bigEndian = false): number {
    const data = Buffer.from(this.readBytes(8));
    return bigEndian ? data.readDoubleBE(0) : data.readDoubleLE(0);
  }

  readCString(): string {
    const chunks: number[] = [];
    while (true) {
      const char = this.readBytes(1)[0];
      if (char === undefined) {
        throw new ParserError("reached end of input");
      }
      if (char === 0) {
        return Buffer.from(chunks).toString();
      }
      chunks.push(char);
    }
  }

  skip(numBytes: number, description = "unknown"): void {
    if (numBytes > 0) {
      this.logger.debug(`skipping ${numBytes} bytes (${description})`);
      this.readBytes(numBytes);
    } else if (numBytes < 0) {
      throw new ParserError(`invalid skip of ${numBytes} bytes`);
    }
  }

  skipTo(offset: number, description = "unknown"): void {
    this.skip(offset - this.cursor, description);
  }

  skipToEnd(description = "unknown"): void {
    this.skipTo(this.data.length, description);
  }
}

export function parseSafariCookies(
  data: Uint8Array,
  jar = new YoutubeDLCookieJar(),
  logger: CookieLogger = new YDLLogger(),
): YoutubeDLCookieJar {
  const [pageSizes, bodyStart] = parseSafariCookiesHeader(data, logger);
  const parser = new DataParser(data.subarray(bodyStart), logger);
  for (const pageSize of pageSizes) {
    parseSafariCookiesPage(parser.readBytes(pageSize), jar, logger);
  }
  parser.skipToEnd("footer");
  return jar;
}

export class LenientSimpleCookie {
  readonly cookies = new Map<string, string>();
  readonly morsels = new Map<string, CookieMorsel>();

  constructor(data?: string) {
    if (data) {
      this.load(data);
    }
  }

  load(data: string): void {
    let morsel: CookieMorsel | null = null;
    for (const match of data.matchAll(COOKIE_PATTERN)) {
      if (match.groups?.bad) {
        morsel = null;
        continue;
      }

      const rawKey = match.groups?.key;
      const rawValue = match.groups?.val;
      if (!rawKey || !LEGAL_COOKIE_KEY_RE.test(rawKey)) {
        morsel = null;
        continue;
      }

      let key = rawKey;
      let isAttribute = false;
      if (key.startsWith("$")) {
        key = key.slice(1);
        isAttribute = true;
      }

      const lowerKey = key.toLocaleLowerCase();
      if (COOKIE_RESERVED_ATTRS.has(lowerKey)) {
        if (!morsel) {
          continue;
        }
        let attrValue: string | true;
        if (rawValue === undefined) {
          if (!COOKIE_FLAG_ATTRS.has(lowerKey)) {
            morsel = null;
            continue;
          }
          attrValue = true;
        } else {
          attrValue = decodeCookieValue(rawValue);
          if (hasCookieControlChar(attrValue)) {
            this.cookies.delete(morsel.key);
            this.morsels.delete(morsel.key);
            morsel = null;
            continue;
          }
        }
        morsel.setAttribute(lowerKey, attrValue);
      } else if (isAttribute) {
        morsel = null;
      } else if (rawValue !== undefined) {
        const realValue = decodeCookieValue(rawValue);
        if (hasCookieControlChar(realValue)) {
          morsel = null;
          continue;
        }
        morsel = this.morsels.get(key) ?? new CookieMorsel();
        morsel.set(key, realValue, rawValue);
        this.morsels.set(key, morsel);
        this.cookies.set(key, realValue);
      } else {
        morsel = null;
      }
    }
  }

  get(key: string): string | undefined {
    return this.cookies.get(key);
  }

  getMorsel(key: string): CookieMorsel | undefined {
    return this.morsels.get(key);
  }

  keys(): IterableIterator<string> {
    return this.morsels.keys();
  }

  values(): IterableIterator<CookieMorsel> {
    return this.morsels.values();
  }
}

export const COOKIE_MORSEL_ATTRIBUTE_KEYS = [
  "expires",
  "path",
  "comment",
  "domain",
  "max-age",
  "secure",
  "httponly",
  "version",
  "samesite",
] as const;

export class CookieMorsel implements Iterable<string> {
  key = "";
  value = "";
  codedValue = "";
  readonly attributes: Record<string, string | true | ""> = Object.fromEntries(
    COOKIE_MORSEL_ATTRIBUTE_KEYS.map((key) => [key, ""]),
  ) as Record<string, string | true | "">;

  [Symbol.iterator](): Iterator<string> {
    return COOKIE_MORSEL_ATTRIBUTE_KEYS[Symbol.iterator]();
  }

  set(key: string, value: string, codedValue = value): void {
    if (!LEGAL_COOKIE_KEY_RE.test(key)) {
      throw new Error(`Illegal key ${key}`);
    }
    this.key = key;
    this.value = value;
    this.codedValue = codedValue;
  }

  setAttribute(key: string, value: string | true): void {
    const lowerKey = key.toLocaleLowerCase();
    if (!COOKIE_RESERVED_ATTRS.has(lowerKey)) {
      throw new Error(`Invalid cookie attribute ${key}`);
    }
    this.attributes[lowerKey] = value;
  }

  update(values: Record<string, string | true>): void {
    for (const [key, value] of Object.entries(values)) {
      this.setAttribute(key, value);
    }
  }

  getAttribute(key: string): string | true | "" {
    return this.attributes[key.toLocaleLowerCase()] ?? "";
  }

  entries(): Array<[string, string | true | ""]> {
    return COOKIE_MORSEL_ATTRIBUTE_KEYS.map((key) => [key, this.attributes[key] ?? ""]);
  }

  values(): Array<string | true | ""> {
    return this.entries().map(([, value]) => value);
  }

  toTraversalRecord(): Record<string, string | true | ""> {
    return Object.fromEntries([
      ...this.entries(),
      ["key", this.key],
      ["value", this.value],
    ]);
  }
}

const COOKIE_RESERVED_ATTRS: Set<string> = new Set(COOKIE_MORSEL_ATTRIBUTE_KEYS);
const COOKIE_FLAG_ATTRS: Set<string> = new Set(["secure", "httponly"]);
const LEGAL_COOKIE_KEY_RE = /^[A-Za-z0-9_!#$%&'*+\-.:^`|~]+$/;
const COOKIE_PATTERN =
  /[ ]*(?<key>[^ =;]+)(?:[ ]*=[ ]*(?:(?<val>"(?:[^\\"]|\\.)*"|[A-Za-z]{3}, [A-Za-z0-9 -]{9,11} [0-9:]{8} GMT|[A-Za-z0-9_!#$%&'*+\-.:^`|~(),/<=>?@[\]{}]*)|(?<bad>(?:\\;|[^;])*?)))?[ ]*(?:[ ]+|;|$)/g;

function decodeCookieValue(value: string): string {
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).replace(/\\([0-3][0-7]{2}|.)/g, (_match, escaped: string) => {
      if (/^[0-3][0-7]{2}$/.test(escaped)) {
        return String.fromCharCode(Number.parseInt(escaped, 8));
      }
      return escaped;
    });
  }
  return value;
}

function hasCookieControlChar(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code <= 0x1f || code === 0x7f) {
      return true;
    }
  }
  return false;
}

function parseNetscapeCookieLine(line: string): Cookie {
  let httpOnly = false;
  if (line.startsWith(YoutubeDLCookieJar.HTTPONLY_PREFIX)) {
    httpOnly = true;
    line = line.slice(YoutubeDLCookieJar.HTTPONLY_PREFIX.length);
  }
  const parts = line.split("\t");
  if (parts.length !== YoutubeDLCookieJar.ENTRY_LEN) {
    throw new Error(`invalid length ${parts.length}`);
  }
  const [domain, , path, secure, expires, name, value] = parts as [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ];
  if (expires && !/^[0-9]+(?:\.[0-9]+)?$/.test(expires)) {
    throw new Error(`invalid expires at ${expires}`);
  }
  return new Cookie({
    domain,
    path,
    secure: secure.toUpperCase() === "TRUE",
    expires: expires ? Number(expires) || null : null,
    name,
    value,
    httpOnly,
    discard: !expires || expires === "0",
  });
}

function cookieMatchesUrl(cookie: Cookie, url: URL, now: number): boolean {
  if (cookie.isExpired(now)) {
    return false;
  }
  if (cookie.secure && url.protocol !== "https:") {
    return false;
  }
  const host = url.hostname.toLowerCase();
  const domain = cookie.domain.replace(/^\./, "").toLowerCase();
  if (host !== domain && !host.endsWith(`.${domain}`)) {
    return false;
  }
  return url.pathname.startsWith(cookie.path || "/");
}

function filterCookieJarForUrl(
  source: YoutubeDLCookieJar,
  url: string,
): YoutubeDLCookieJar {
  const jar = new YoutubeDLCookieJar();
  for (const cookie of source.getCookiesForUrl(url)) {
    jar.setCookie(cookie);
  }
  return jar;
}

function sweetCookieOptions(
  browserName: string,
  profile: string | null,
  url: string,
): GetCookiesOptions | null {
  const options: GetCookiesOptions = {
    url,
    mode: "merge",
    includeExpired: false,
    timeoutMs: 5000,
  };
  if (browserName === "firefox") {
    options.browsers = ["firefox"];
    if (profile) {
      options.firefoxProfile = profile;
    }
    return options;
  }
  if (browserName === "safari") {
    options.browsers = ["safari"];
    if (profile) {
      options.safariCookiesFile = profile;
    }
    return options;
  }
  if (browserName === "edge") {
    options.browsers = ["edge"];
    if (profile) {
      options.edgeProfile = profile;
    }
    return options;
  }
  const chromiumBrowser = sweetChromiumBrowser(browserName);
  if (chromiumBrowser) {
    options.browsers = ["chrome"];
    if (profile) {
      options.chromeProfile = profile;
    }
    if (process.platform === "darwin") {
      options.chromiumBrowser = chromiumBrowser;
    }
    return options;
  }
  return null;
}

function sweetChromiumBrowser(
  browserName: string,
): GetCookiesOptions["chromiumBrowser"] | null {
  if (browserName === "chrome") {
    return "chrome";
  }
  if (browserName === "brave") {
    return "brave";
  }
  if (browserName === "chromium") {
    return "chromium";
  }
  return null;
}

function sweetCookieToYtdlbCookie(
  cookie: SweetCookie,
  requestUrl: string,
): Cookie {
  const parsed = new URL(cookie.url ?? requestUrl);
  const domain = cookie.domain ?? parsed.hostname;
  return new Cookie({
    name: cookie.name,
    value: cookie.value,
    domain,
    path: cookie.path ?? "/",
    secure: cookie.secure ?? parsed.protocol === "https:",
    expires: cookie.expires ?? null,
    httpOnly: cookie.httpOnly ?? false,
    discard: cookie.expires === undefined,
  });
}

function firefoxBrowserDirs(): string[] {
  if (process.platform === "win32") {
    return [
      expandEnv("%APPDATA%\\Mozilla\\Firefox\\Profiles"),
      expandEnv(
        "%LOCALAPPDATA%\\Packages\\Mozilla.Firefox_n80bbvh6b1yt2\\LocalCache\\Roaming\\Mozilla\\Firefox\\Profiles",
      ),
    ];
  }
  if (process.platform === "darwin") {
    return [expandPath("~/Library/Application Support/Firefox/Profiles")];
  }
  return [
    join(configHome(), "mozilla/firefox"),
    expandPath("~/.mozilla/firefox"),
    expandPath("~/.var/app/org.mozilla.firefox/config/mozilla/firefox"),
    expandPath("~/.var/app/org.mozilla.firefox/.mozilla/firefox"),
    expandPath("~/snap/firefox/common/.mozilla/firefox"),
  ];
}

async function firefoxCookieDbs(roots: readonly string[]): Promise<string[]> {
  const files: string[] = [];
  for (const root of roots.map((path) => resolve(path))) {
    files.push(...(await findFiles(root, "cookies.sqlite")));
  }
  return files;
}

function getChromiumBasedBrowserSettings(browserName: string): {
  browserDir: string;
  keyringName: string;
  supportsProfiles: boolean;
} {
  const config = configHome();
  const home = process.env.HOME ?? "";
  const platformDirs: { dir: Record<string, string> } =
    process.platform === "darwin"
      ? {
          dir: {
            brave: "~/Library/Application Support/BraveSoftware/Brave-Browser",
            chrome: "~/Library/Application Support/Google/Chrome",
            chromium: "~/Library/Application Support/Chromium",
            edge: "~/Library/Application Support/Microsoft Edge",
            opera: "~/Library/Application Support/com.operasoftware.Opera",
            vivaldi: "~/Library/Application Support/Vivaldi",
            whale: "~/Library/Application Support/Naver/Whale",
          },
        }
      : process.platform === "win32"
        ? {
            dir: {
              brave: "%LOCALAPPDATA%\\BraveSoftware\\Brave-Browser\\User Data",
              chrome: "%LOCALAPPDATA%\\Google\\Chrome\\User Data",
              chromium: "%LOCALAPPDATA%\\Chromium\\User Data",
              edge: "%LOCALAPPDATA%\\Microsoft\\Edge\\User Data",
              opera: "%APPDATA%\\Opera Software\\Opera Stable",
              vivaldi: "%LOCALAPPDATA%\\Vivaldi\\User Data",
              whale: "%LOCALAPPDATA%\\Naver\\Naver Whale\\User Data",
            },
          }
        : {
            dir: {
              brave: join(config, "BraveSoftware/Brave-Browser"),
              chrome: join(config, "google-chrome"),
              chromium: join(config, "chromium"),
              edge: join(config, "microsoft-edge"),
              opera: join(config, "opera"),
              vivaldi: join(config, "vivaldi"),
              whale: join(config, "naver-whale"),
            },
          };
  const keyringName: Record<string, string> = {
    brave: "Brave",
    chrome: "Chrome",
    chromium: "Chromium",
    edge: process.platform === "darwin" ? "Microsoft Edge" : "Chromium",
    opera: process.platform === "darwin" ? "Opera" : "Chromium",
    vivaldi: process.platform === "darwin" ? "Vivaldi" : "Chrome",
    whale: "Whale",
  };
  return {
    browserDir: expandEnv(
      platformDirs.dir[browserName]?.replace(/^~/, home) ?? "",
    ),
    keyringName: keyringName[browserName] ?? "Chrome",
    supportsProfiles: browserName !== "opera",
  };
}

type FirefoxRow = {
  host: string;
  name: string;
  value: string;
  path: string;
  expiry: number | null;
  isSecure: number;
};

function queryFirefoxRows(
  db: Database,
  container: string | null,
  containerId: number | null,
): FirefoxRow[] {
  if (typeof containerId === "number") {
    return db
      .query(
        "SELECT host, name, value, path, expiry, isSecure FROM moz_cookies WHERE originAttributes LIKE $a OR originAttributes LIKE $b",
      )
      .all({
        $a: `%userContextId=${containerId}`,
        $b: `%userContextId=${containerId}&%`,
      }) as FirefoxRow[];
  }
  if (container === "none") {
    return db
      .query(
        'SELECT host, name, value, path, expiry, isSecure FROM moz_cookies WHERE NOT INSTR(originAttributes,"userContextId=")',
      )
      .all() as FirefoxRow[];
  }
  return db
    .query("SELECT host, name, value, path, expiry, isSecure FROM moz_cookies")
    .all() as FirefoxRow[];
}

type ChromeCookieRow = {
  host_key: string | Uint8Array;
  name: string | Uint8Array;
  value: string | Uint8Array;
  encrypted_value: Uint8Array | null;
  path: string | Uint8Array;
  expires_utc: number | null;
  is_secure: number;
};

function processChromeCookie(
  decryptor: ChromeCookieDecryptor,
  row: ChromeCookieRow,
): [boolean, Cookie | null] {
  const hostKey = bufferishToString(row.host_key);
  const name = bufferishToString(row.name);
  let value = bufferishToString(row.value);
  const path = bufferishToString(row.path);
  const encryptedValue = row.encrypted_value;
  const encrypted =
    !value && encryptedValue !== null && encryptedValue.length > 0;
  if (encrypted) {
    value = decryptor.decrypt(encryptedValue) ?? "";
    if (!value) {
      return [true, null];
    }
  }
  return [
    Boolean(encrypted),
    new Cookie({
      name,
      value,
      domain: hostKey,
      path,
      secure: Boolean(row.is_secure),
      expires: row.expires_utc || null,
      discard: false,
    }),
  ];
}

function parseSafariCookiesHeader(
  data: Uint8Array,
  logger: CookieLogger,
): [number[], number] {
  const parser = new DataParser(data, logger);
  parser.expectBytes(Buffer.from("cook"), "database signature");
  const pages = parser.readUint(true);
  return [
    Array.from({ length: pages }, () => parser.readUint(true)),
    parser.cursor,
  ];
}

function parseSafariCookiesPage(
  data: Uint8Array,
  jar: YoutubeDLCookieJar,
  logger: CookieLogger,
): void {
  const parser = new DataParser(data, logger);
  parser.expectBytes(Buffer.from([0, 0, 1, 0]), "page signature");
  const cookieCount = parser.readUint();
  const offsets = Array.from({ length: cookieCount }, () => parser.readUint());
  if (!cookieCount) {
    logger.debug(`a cookies page of size ${data.length} has no cookies`);
    return;
  }
  const firstOffset = offsets[0];
  if (firstOffset === undefined) {
    throw new Error("Safari cookies page has no first cookie offset");
  }
  parser.skipTo(firstOffset, "unknown page header field");
  for (const offset of offsets) {
    parser.skipTo(offset, "space between records");
    const recordLength = parseSafariCookiesRecord(
      data.subarray(offset),
      jar,
      logger,
    );
    parser.readBytes(recordLength);
  }
  parser.skipToEnd("space in between pages");
}

function parseSafariCookiesRecord(
  data: Uint8Array,
  jar: YoutubeDLCookieJar,
  logger: CookieLogger,
): number {
  const parser = new DataParser(data, logger);
  const recordSize = parser.readUint();
  parser.skip(4, "unknown record field 1");
  const flags = parser.readUint();
  const secure = Boolean(flags & 0x0001);
  parser.skip(4, "unknown record field 2");
  const domainOffset = parser.readUint();
  const nameOffset = parser.readUint();
  const pathOffset = parser.readUint();
  const valueOffset = parser.readUint();
  parser.skip(8, "unknown record field 3");
  const firstStringOffset = safariStringOffset(
    Math.min(domainOffset, nameOffset, pathOffset, valueOffset),
  );
  const dateParser = new DataParser(
    data.subarray(Math.max(0, firstStringOffset - 16)),
    logger,
  );
  const expirationDate = macAbsoluteTimeToPosix(dateParser.readDouble());
  dateParser.readDouble();

  try {
    const domain = readSafariCString(data, domainOffset, logger);
    const name = readSafariCString(data, nameOffset, logger);
    const path = readSafariCString(data, pathOffset, logger);
    const value = readSafariCString(data, valueOffset, logger);
    parser.skipTo(recordSize, "space at the end of the record");
    jar.setCookie(
      new Cookie({
        name,
        value,
        domain,
        path,
        secure,
        expires: expirationDate,
        discard: false,
      }),
    );
  } catch {
    logger.warning(
      "failed to parse Safari cookie because UTF-8 decoding failed",
      { onlyOnce: true },
    );
  }
  return recordSize;
}

function safariStringOffset(offset: number): number {
  return Math.max(0, offset - 1);
}

function readSafariCString(
  data: Uint8Array,
  offset: number,
  logger: CookieLogger,
): string {
  return new DataParser(
    data.subarray(safariStringOffset(offset)),
    logger,
  ).readCString();
}

function macAbsoluteTimeToPosix(timestamp: number): number {
  return Math.trunc(Date.UTC(2001, 0, 1) / 1000 + timestamp);
}

export function getLinuxDesktopEnvironment(
  env: Record<string, string | number | undefined>,
  logger: CookieLogger = new YDLLogger(),
): LinuxDesktopEnvironment {
  const xdgCurrentDesktop = env.XDG_CURRENT_DESKTOP;
  const desktopSession = String(env.DESKTOP_SESSION ?? "");
  if (xdgCurrentDesktop !== undefined) {
    for (const part of String(xdgCurrentDesktop)
      .split(":")
      .map((item) => item.trim())) {
      if (part === "Unity") {
        return desktopSession.includes("gnome-fallback")
          ? LinuxDesktopEnvironment.GNOME
          : LinuxDesktopEnvironment.UNITY;
      }
      if (part === "Deepin") {
        return LinuxDesktopEnvironment.DEEPIN;
      }
      if (part === "GNOME") {
        return LinuxDesktopEnvironment.GNOME;
      }
      if (part === "X-Cinnamon") {
        return LinuxDesktopEnvironment.CINNAMON;
      }
      if (part === "KDE") {
        const kdeVersion = env.KDE_SESSION_VERSION;
        if (kdeVersion === "5") {
          return LinuxDesktopEnvironment.KDE5;
        }
        if (kdeVersion === "6") {
          return LinuxDesktopEnvironment.KDE6;
        }
        if (kdeVersion === "4") {
          return LinuxDesktopEnvironment.KDE4;
        }
        logger.info(`unknown KDE version: "${kdeVersion}". Assuming KDE4`);
        return LinuxDesktopEnvironment.KDE4;
      }
      if (part === "Pantheon") {
        return LinuxDesktopEnvironment.PANTHEON;
      }
      if (part === "XFCE") {
        return LinuxDesktopEnvironment.XFCE;
      }
      if (part === "UKUI") {
        return LinuxDesktopEnvironment.UKUI;
      }
      if (part === "LXQt") {
        return LinuxDesktopEnvironment.LXQT;
      }
    }
    logger.debug(
      `XDG_CURRENT_DESKTOP is set to an unknown value: "${xdgCurrentDesktop}"`,
    );
  }

  if (desktopSession === "deepin") {
    return LinuxDesktopEnvironment.DEEPIN;
  }
  if (desktopSession === "mate" || desktopSession === "gnome") {
    return LinuxDesktopEnvironment.GNOME;
  }
  if (desktopSession === "kde4" || desktopSession === "kde-plasma") {
    return LinuxDesktopEnvironment.KDE4;
  }
  if (desktopSession === "kde") {
    return "KDE_SESSION_VERSION" in env
      ? LinuxDesktopEnvironment.KDE4
      : LinuxDesktopEnvironment.KDE3;
  }
  if (desktopSession.includes("xfce") || desktopSession === "xubuntu") {
    return LinuxDesktopEnvironment.XFCE;
  }
  if (desktopSession === "ukui") {
    return LinuxDesktopEnvironment.UKUI;
  }
  logger.debug(
    `DESKTOP_SESSION is set to an unknown value: "${desktopSession}"`,
  );

  if ("GNOME_DESKTOP_SESSION_ID" in env) {
    return LinuxDesktopEnvironment.GNOME;
  }
  if ("KDE_FULL_SESSION" in env) {
    return "KDE_SESSION_VERSION" in env
      ? LinuxDesktopEnvironment.KDE4
      : LinuxDesktopEnvironment.KDE3;
  }
  return LinuxDesktopEnvironment.OTHER;
}

function getLinuxKeyringPassword(
  _browserKeyringName: string,
  keyring: string | null,
  logger: CookieLogger,
): Buffer | null {
  if (keyring === LinuxKeyring.BASICTEXT) {
    return Buffer.alloc(0);
  }
  // Logic change: Python shells out to DBus/keyring tools or imports secretstorage. The Bun layer
  // avoids those Python dependencies and currently supports only Chromium's basic-text path.
  logger.warning(
    "Linux keyring cookie decryption is not implemented in ytdlb; use keyring BASICTEXT or cookies.txt",
    { onlyOnce: true },
  );
  throw new NotImplementedError("Linux keyring cookie decryption");
}

function getMacKeyringPassword(
  _browserKeyringName: string,
  logger: CookieLogger,
): Buffer | null {
  logger.warning(
    "macOS keychain cookie decryption is not implemented in ytdlb; use cookies.txt for encrypted Chromium cookies",
    { onlyOnce: true },
  );
  throw new NotImplementedError("macOS keychain cookie decryption");
}

function getWindowsV10Key(
  _browserRoot: string,
  logger: CookieLogger,
): Buffer | null {
  logger.warning(
    "Windows DPAPI cookie decryption is not implemented in ytdlb; use cookies.txt for encrypted Chromium cookies",
    { onlyOnce: true },
  );
  throw new NotImplementedError("Windows DPAPI cookie key decryption");
}

function decryptWindowsDpapi(
  _ciphertext: Uint8Array,
  logger: CookieLogger,
): Buffer | null {
  logger.warning(
    "Windows DPAPI cookie decryption is not implemented in ytdlb",
    { onlyOnce: true },
  );
  throw new NotImplementedError("Windows DPAPI cookie decryption");
}

function deriveLinuxKey(password: Uint8Array): Buffer {
  return pbkdf2Sha1(password, Buffer.from("saltysalt"), 1, 16);
}

function decodeUtf8Maybe(data: Uint8Array): string | null {
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(data);
  } catch {
    return null;
  }
}

async function openDatabaseCopy(
  databasePath: string,
  tmp: string,
): Promise<string> {
  const databaseCopyPath = join(tmp, "temporary.sqlite");
  await copyFile(databasePath, databaseCopyPath);
  return databaseCopyPath;
}

function getColumnNames(db: Database, tableName: string): string[] {
  const safeTable = tableName.replaceAll(/[^A-Za-z0-9_]/g, "");
  return (
    db.query(`PRAGMA table_info(${safeTable})`).all() as Array<{ name: string }>
  ).map((row) => row.name);
}

async function newest(files: readonly string[]): Promise<string | null> {
  let result: string | null = null;
  let resultMtime = -Infinity;
  for (const file of files) {
    try {
      const info = await stat(file);
      if (info.mtimeMs > resultMtime) {
        result = file;
        resultMtime = info.mtimeMs;
      }
    } catch {}
  }
  return result;
}

async function findFiles(root: string, filename: string): Promise<string[]> {
  const result: string[] = [];
  async function walk(dir: string): Promise<void> {
    let entries: string[];
    try {
      entries = await readdir(dir);
    } catch {
      return;
    }
    await Promise.all(
      entries.map(async (entry) => {
        const full = join(dir, entry);
        const info = await stat(full).catch(() => null);
        if (!info) {
          return;
        }
        if (info.isDirectory()) {
          await walk(full);
        } else if (basename(full) === filename) {
          result.push(full);
        }
      }),
    );
  }
  await walk(root);
  return result;
}

function mergeCookieJars(
  jars: readonly YoutubeDLCookieJar[],
): YoutubeDLCookieJar {
  const output = new YoutubeDLCookieJar();
  for (const jar of jars) {
    for (const cookie of jar) {
      output.setCookie(cookie);
    }
    if (jar.filename) {
      output.filename = jar.filename;
    }
  }
  return output;
}

function parseBrowserSpecification(
  browserName: string,
  profile?: string | null,
  keyring?: string | null,
  container?: string | null,
): [string, string | null, string | null, string | null] {
  if (!SUPPORTED_BROWSERS.has(browserName)) {
    throw new Error(`unsupported browser: "${browserName}"`);
  }
  if (keyring && !SUPPORTED_KEYRINGS.includes(keyring)) {
    throw new Error(`unsupported keyring: "${keyring}"`);
  }
  const expandedProfile =
    profile && isPath(expandPath(profile))
      ? expandPath(profile)
      : (profile ?? null);
  return [browserName, expandedProfile, keyring ?? null, container ?? null];
}

function isPath(value: string): boolean {
  return value.includes("/") || value.includes("\\");
}

function configHome(): string {
  return process.env.XDG_CONFIG_HOME ?? expandPath("~/.config");
}

function expandPath(path: string): string {
  if (path === "~") {
    return process.env.HOME ?? path;
  }
  if (path.startsWith("~/")) {
    return join(process.env.HOME ?? "~", path.slice(2));
  }
  return expandEnv(path);
}

function expandEnv(path: string): string {
  return path.replaceAll(
    /%([^%]+)%/g,
    (_, key: string) => process.env[key] ?? `%${key}%`,
  );
}

async function fileExists(path: string | null): Promise<boolean> {
  if (!path) {
    return false;
  }
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

function trueOrFalse(value: boolean): "TRUE" | "FALSE" {
  return value ? "TRUE" : "FALSE";
}

function bufferishToString(value: string | Uint8Array | null): string {
  if (typeof value === "string") {
    return value;
  }
  if (!value) {
    return "";
  }
  return Buffer.from(value).toString();
}

export const _LinuxKeyring = LinuxKeyring;
export const YoutubeDLError = Error;
